on:
  push:
    branches: [org.jeffvli.feishin]
name: CI
jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-44
      options: --privileged
    steps:
    - uses: actions/checkout@v3
    - uses: flatpak/flatpak-github-actions/flatpak-builder@v6.1
      with:
        bundle: feishin.flatpak
        manifest-path: org.jeffvli.feishin.yml
        cache-key: flatpak-builder-${{ github.sha }}
